name: Build latest package
on: 
  push:
    branches:
      - master
      - main

env:
  PAT_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: yarn

      - name: Check TypeScript errors
        run: yarn tsc --noEmit
        
      # - name: Build project
      #   run: yarn build

      - name: Get package version number
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      
      - name: Tag new version
        uses: pkgdeps/action-package-version-to-git-tag@v1.5.0
        with:
          version: ${{ steps.package-version.outputs.current-version}}
          git_tag_prefix: "v"
          github_token: ${{ env.PAT_GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
