name: Build latest package
on: 
  push:
    branches:
      - master
      - main

env:
  PAT_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: yarn

      - name: Test orm
        run: yarn test-orm
        
      - name: Build project
        run: yarn build

      - name: Get package version number
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      
      - name: Tag new version
        uses: pkgdeps/action-package-version-to-git-tag@v1.5.0
        with:
          version: ${{ steps.package-version.outputs.current-version}}
          git_tag_prefix: "v"
          github_token: ${{ env.PAT_GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
